services:
  app:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: purwa-digital
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production

networks:
  default:
    external: true
    name: global-network
